### ISSUE TITLE
Log周りのshcemaについて

### ISSUE THREAD

**Issue by Hunachi** [MeetLog/meet-log-share#4]
```
Message{
    imageUrls: [String]
    comment: String
   ...
}
Log{
 sessionId: String
 participants: [User]
 date: String
 place: String!
 messages: [Message]
}

getLog(
    sessionId: String
): Log

getLogs(): [Log]

```

**Comment by mirror-kt** [comment]
snake_caseかcamelCaseに統一しませんか

**Comment by mirror-kt** [comment]
`getLogs(): [Log]`は、全エンカの全Logを返却するってことであってます？(なんに使うんだろう？)
GraphQLの利点として全エンカを取得後各エンカのLogを取得まで一発のリクエストで行けた気がするので(違ったらごめんなさい)必要性がわからないです…

**Comment by mirror-kt** [comment]
想定として`MeetSession`は一対一を指すものとしていますが、ここで提示してる`Log`は一対多になっている気がするのでどうやって整合性を取るかですね…
(よく考えると`getSession(myId, friendsId)`は使い所がない…)

**Comment by Hunachi** [comment]
現時点でのgetSessionのMeetSessionがなんなのかがよくわかってないから教えて欲しい！例えばfriendが複数人いる場合MeetSessionはどうなるの？

**Comment by Hunachi** [comment]
あと、LogとMeetSessionは多対一の関係であってる？
https://github.com/MeetLog/meet-log-share/issues/4#issuecomment-575992762
ユビキタス言語が決まってないから全然違うこと言ってるように見えるだけで、私が言いたいのは、getMeetSessions（これをgetLogsと言ってた）が欲しいということでキョウくんと考えは同じな気がする（間違ってるかも）

**Comment by mirror-kt** [comment]
`MeetSession` 
ある2人がアカウントを交換した、という状態を表す。
IDはこの2人の組み合わせに対してユニーク(他の組み合わせだと別のIDが返る)。

`connectAccount`
myIdとfriendsIdが入れ替わっても同じIDを持つMeetSessionが帰ってくるが、どちらがどちらかによってaccountsの中身が変わる(friendsId側のユーザーのaccountsが返る。)

`Log`
1つのMeetSessionに対して複数のLogを持ちうる。
あくまで2人の間でのLogになる。

複数人でアカウントを交換した場合
一対一が複数存在すると考える。
写真が重複する気もするけどそれはどうしようか…。
多対多にすると、どのMeetSessionにユーザーを追加すべきかなど色々面倒になる。

**Comment by mirror-kt** [comment]
MeetSessionに`logs: [Log]`をつけて、postLogされたやつは全部ここに来るようにすれば`getLogs(sessionId)`がいらなくなる？

**Comment by Hunachi** [comment]
`MeetGroupSession` or  `MeetSession`を`FriendSession`に変えて違う意味の`MeetSession`
みたいなMeetSessionとLogの中間の遊んだ時に毎回発行されるSession（日時や場所、Logsを持っている）が欲しい気持ちになってる。

getLogsに関しては、特定のfriendや日時を指定できた方があとで楽かもだからそれらを設定する引数は残しといてもらえると助かる！

**Comment by mirror-kt** [comment]
> `MeetGroupSession` or `MeetSession`を`FriendSession`に変えて違う意味の`MeetSession`
> みたいなMeetSessionとLogの中間の遊んだ時に毎回発行されるSession（日時や場所、Logsを持っている）が欲しい気持ちになってる。

`MeetGroupSession` -> `[MeetSession]` -> `[Log]`
ですかね？
1対1を束ねて場所とか時間を保持するものがほしいという認識であってますか？

**Comment by Hunachi** [comment]
そう！それであってる。どうかな 🤔 💭

**Comment by Hunachi** [comment]
```
type MeetSession{
    id: String
    participants: [User]
    date: String
    place: String!
    logs: [Log]
}
```

**Comment by mirror-kt** [comment]
この場合におけるMeetSessionを特定する方法がなくないですか…？
(あった人たちの誰かが全員と交換して作成したMeetSessionにinviteするみたいな実装になりそう)

**Comment by mirror-kt** [comment]
変にやると同じメンバーの同じ場所の同じ時間を指すMeetSessionが複数できてしまいそうっていうのがちょっと懸念

**Comment by Hunachi** [comment]
MeetSessionにinviteする感じになると思う。グループで共有ができないのは辛いからgroupに誘う画面作ろうかなと…（そのinviteするための画面を開いたままタッチすればグループに入りつつそのタッチした人とは友達になるみたいな。）

**Comment by mirror-kt** [comment]
んじゃ
* 今のMeetSessionをFriendSessionにRename
* MeetGroupSessionを新規作成
* FriendSessionに所属するMeetGroupSessionのIDを保持

で良さそうですかね？
inviteのQueryをどうするかってのも考えなきゃですけど

**Comment by Hunachi** [comment]
inviteするときのQueryは、別で作るのもありだし、
getSessionにgroupSessionIdの引数を追加するのもありな気がする。

**Comment by Hunachi** [comment]
FriendsSession発酵時にすでに誘うかどうか決めてるならだけど…
あとはいつ解散にするかやな。`leaveMeetSession / goodbyeMeetSession`的なクエリもいりそうかもだ。

**Comment by mirror-kt** [comment]
NFCでgroupSessionIdを渡す->getSession(myId, friendId, groupSessionId): FriendSession
か

**Comment by Hunachi** [comment]
とても良いと思う。

**Comment by mirror-kt** [comment]
最初のユーザーがGroupSessionを作るクエリもいる
最初に自分が参加する必要があるから
`createGroupSession(myId): GroupSession!`
かな？

**Comment by mirror-kt** [comment]
> FriendsSession発酵時にすでに誘うかどうか決めてるならだけど…
> あとはいつ解散にするかやな。`leaveMeetSession / goodbyeMeetSession`的なクエリもいりそうかもだ。

解散ってのはendTimeのことかな？

**Comment by Hunachi** [comment]
けどすでにMeetSesssionを発行しちゃってて後からGroupに参加したいみたいなときはもう一度getSessionする感じでいいか。

**Comment by Hunachi** [comment]
https://github.com/MeetLog/meet-log-share/issues/4#issuecomment-576002821
🙆‍♂️
個人個人で抜けるタイミングを決められた方がいいかなって思う。

**Comment by mirror-kt** [comment]
> [#4 (comment)](https://github.com/MeetLog/meet-log-share/issues/4#issuecomment-576002821)
> 🙆‍♂️
> 個人個人で抜けるタイミングを決められた方がいいかなって思う。

map<User, EndTime>みたいにしないと無理くないですか？

**Comment by Hunachi** [comment]
そうなりそう。（サーバー側が考えること多くなりそう）

**Comment by mirror-kt** [comment]
`leaveMeetSession(meetSessionId, myId, endTime)`でいいのか

**Comment by Hunachi** [comment]
クライアント的にはそれが助かります！

**Comment by mirror-kt** [comment]
this issue was solved by #5
